import { createFileRoute } from "@tanstack/react-router";

import { PageShell, Section, pageMeta } from "@/components/site/page";

export const Route = createFileRoute("/disclaimer")({
  head: () =>
    pageMeta({
      title: "Disclaimer — Pixflow AI",
      description:
        "Important notes about AI generated content, accuracy, third-party services and external links on Pixflow AI.",
      path: "/disclaimer",
    }),
  component: DisclaimerPage,
});

function DisclaimerPage() {
  return (
    <PageShell title="Disclaimer" intro="Last updated: 4 August 2026">
      <Section title="AI generated content">
        <p>
          Images produced by Pixflow AI are generated by machine learning models. They may contain
          inaccuracies, visual artefacts or unintended resemblances. Always review output before
          publishing it.
        </p>
      </Section>
      <Section title="No professional advice">
        <p>
          Articles on this site are general information only and are not legal, financial or
          professional advice. Consult a qualified professional for your specific situation.
        </p>
      </Section>
      <Section title="Third-party services">
        <p>
          Generation relies on third-party AI providers. We do not control their models, filters or
          availability, and we are not responsible for their output.
        </p>
      </Section>
      <Section title="External links">
        <p>
          Links to other websites are provided for convenience. We do not endorse and are not
          responsible for their content or practices.
        </p>
      </Section>
      <Section title="Your responsibility">
        <p>
          You are responsible for how you use generated images, including compliance with copyright,
          publicity and platform rules in your country.
        </p>
      </Section>
    </PageShell>
  );
}